
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import './globals.css'
import { cookies } from 'next/headers'
import LogoutButton from '@/components/LogoutButton'
import Link from 'next/link'
import Header from '@/components/Header/Header'
import PersistentDrawer from '@/components/Drawer/PersistentDrawer'
import Layout from '@/components/Layout'
import { Outlet, useLocation } from 'react-router-dom'
import { Typography } from '@mui/material'
import Box from '@mui/material/Box';

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        {/* <Header title ="pink-elephant" user = {user} /> */}
        <PersistentDrawer title="pink-elephant" user = {user}/>
        <Box ml={10} mt={5}>
          {children}
        </Box>
      </body>
    </html>
  )
}
