import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import './globals.css'
import { cookies } from 'next/headers'
import DeployButton from '@/components/DeployButton'
import LogoutButton from '@/components/LogoutButton'
import Link from 'next/link'


export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            {user ? (
              <div>
                Hey, {user.email}!
                <LogoutButton />
              </div>
            ) : (
              <Link href="/login">
                Login
              </Link>
            )}
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
