import { cookies } from "next/headers"
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import Header from "@/components/Layout/Header"
import "./globals.css"
import { Container } from "@mui/material"
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export const dynamic = "force-dynamic"

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user }
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <main>
          <ThemeRegistry>
            <Header
              title={"pink-elephant"}
              user={user}
            />
            <Container
              sx={{
                display: "flex",
                justifyContent: "center",
                flexDirection: "column",
                p: 6,
                ml: 10
              }}
            >
              {children}
            </Container>
          </ThemeRegistry>
        </main>
      </body>
    </html>
  )
}